import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.tsdlab.com/">TSD</a>
        </h1>

        <p className={styles.description}>
          This is the <b>3D lab's</b> incoming supply inspection page.<br>
          </br>        
          It's meant to help us inspect all incoming deliverables that feed our processes.
          <br></br>This allows us to catch defects that would infect our deliverables to our internal customers.
        </p>

        <div className={styles.grid}>
          <a href="https://docs.google.com/forms/d/e/1FAIpQLSc7SOdLxnnQ_6tflBub8RLr9pktIHwv5XRbi6JvvjSWoQZlDg/viewform" className={styles.card}>
            <h2>Documentation of defects &rarr;</h2>
            <p>Here is where you will document all errors and defects on your incoming supplies and requests.</p>
          </a>

          <a href="https://tsdrolando.wixsite.com/rolando-manso" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about the 3D print lab's current Czar!</p>
          </a>

          <a
            href="https://docs.google.com/spreadsheets/d/1rhhMFDBpNs28QK4EhNFB5ukpfqxPcfE6rxWflLVQROc/edit?resourcekey#gid=1246845015"
            className={styles.card}
          >
            <h2>Review &rarr;</h2>
            <p>See examples of properly documented defects or review your entries.</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Rolo's imagination!
         
        </a>
      </footer>
    </div>
  )
}
